# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\x12\tinference\"4\n\x0bInitRequest\x12\x13\n\x0bmodel_layer\x18\x01 \x01(\x0c\x12\x10\n\x08layer_id\x18\x02 \x01(\x05\"0\n\x0cInitResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"H\n\x0cLayerRequest\x12\x14\n\x0cinput_tensor\x18\x01 \x01(\x0c\x12\x10\n\x08layer_id\x18\x02 \x01(\x05\x12\x10\n\x08is_final\x18\x03 \x01(\x08\"N\n\rLayerResponse\x12\x15\n\routput_tensor\x18\x01 \x01(\x0c\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x15\n\rerror_message\x18\x03 \x01(\t\"%\n\x10HeartbeatRequest\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\"[\n\x11HeartbeatResponse\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\x17\n\x0fgpu_utilization\x18\x02 \x01(\x02\x12\x1a\n\x12memory_utilization\x18\x03 \x01(\x02\x32\xe2\x01\n\x10InferenceService\x12\x41\n\x0cProcessLayer\x12\x17.inference.LayerRequest\x1a\x18.inference.LayerResponse\x12\x43\n\x10InitializeWorker\x12\x16.inference.InitRequest\x1a\x17.inference.InitResponse\x12\x46\n\tHeartbeat\x12\x1b.inference.HeartbeatRequest\x1a\x1c.inference.HeartbeatResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INITREQUEST']._serialized_start=30
  _globals['_INITREQUEST']._serialized_end=82
  _globals['_INITRESPONSE']._serialized_start=84
  _globals['_INITRESPONSE']._serialized_end=132
  _globals['_LAYERREQUEST']._serialized_start=134
  _globals['_LAYERREQUEST']._serialized_end=206
  _globals['_LAYERRESPONSE']._serialized_start=208
  _globals['_LAYERRESPONSE']._serialized_end=286
  _globals['_HEARTBEATREQUEST']._serialized_start=288
  _globals['_HEARTBEATREQUEST']._serialized_end=325
  _globals['_HEARTBEATRESPONSE']._serialized_start=327
  _globals['_HEARTBEATRESPONSE']._serialized_end=418
  _globals['_INFERENCESERVICE']._serialized_start=421
  _globals['_INFERENCESERVICE']._serialized_end=647
# @@protoc_insertion_point(module_scope)
